name: publish
on:
  push:
    branches:
        main
  release:
    types: [published]
jobs:
  publish image:
    runs on: ubuntu latest
    permission:
      content: read
      packages: write
    steps:
      name: Checkout
      uses: actions/checkout@v4
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/rifki227/belajar-ci-cd
        tags: latest
      name: login to GHCR
      uses: docker/login.action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.repository_owner}}
        password:
