name: publish
on:
  push:
    branches:
        main
  release:
    types: [published]
jobs:
  publish image:
    runs on: ubuntu latest
    permission:
      content: read
      packages: write
    steps:
      name: Checkout
      uses: actions/checkout@v4
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/rifki227/belajar-ci-cd
        tags: latest
      name: login to GHCR
      uses: docker/login.action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      name: lint-dockerfile
      user: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
      name: Build Container
      user: docker/build-push-action@v5
      with:
        context:
        push: true
        labels: {{ steps.meta.outputs.labels }}
        labels: {{ steps.meta.outputs.labels }}, ghcr.io/rifki227/belajar-ci-cd
